### ISSUE TITLE
Extension for LTN - Logistic Train Network

### ISSUE THREAD

**Issue by Technickfreak** [digital-pet/signalized-couplers#4]
I think it would be cool if the mods "LTN - Logistic Train Network" and "Signalized Couplers" can work together.

so that stations can order 3 empty wagons
and when these are loaded
enable a locomotive to pick up the wagons.

At first glance, these are only tasks for the LTN programmers, but I easily overlook something.

Link to the other mod:
https://mods.factorio.com/mod/LogisticTrainNetwork

Link to the other issue:
https://github.com/Yousei9/Logistic-Train-Network/issues/223#issue-679578111

**Comment by digital-pet** [comment]
I don't think that is within the scope of this mod, but I feel it would be a great opportunity for a mod on top of LTN. The form it would likely take is a mod that depends on LTN and reuses code from this project (such as the functions which determine train orientation and actually trigger the coupling events) without inheriting the specific signal-to-decouple mechanic this mod adds.

**Comment by Technickfreak** [comment]
Ich bin nicht wirklich gut im Programmieren von Mods, aber ich habe angefangen, LTN so anzupassen, dass zumindest einige der Funktionen gegeben sind. Ich habe es bekommen, damit ich Züge mit Spurweitenwagen zu einem Bahnhof schicken kann und wenn kein Zug mit der richtigen Anzahl von Wagen im Depot ist, dann kann eine Rangierlok Wagen abholen und abliefern.

aber ich traue mich nicht, dies auf einen eigenen Mod umzuprogrammieren. aber wenn du einen Mod mit den Änderungen in LTN erstellen kannst, kann ich sie an dich weitergeben.
